name: Build and Release
on:
  release:
    types: [published]

jobs:
  build_and_release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Update to a more stable and supported version
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install -g nexe

      - name: Build artifacts
        run: make

      - name: Release artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'kubeopenapi-jsonschema*'
          allowUpdates: true
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          token: ${{ secrets.GITHUB_TOKEN }}
