name: Build
on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Update to a supported LTS version
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install -g nexe

      - name: Build artifacts
        run: make all
